image: Visual Studio 2015

# Should only be triggered by schedule run
skip_tags: true
branches:
  only:
    - nonexisted

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: Hj73NIE1ZHUH7DGShakR4Q==
  GITHUB_USER:
    secure: qozx3wkmakdI3k/sz9Ml8Q==
  GITHUB_EMAIL:
    secure: Xou4FEHMweGQSeay5Q9/LjoLWwlDzMmBa39KYVylgK0=
  GITHUB_TOKEN:
    secure: HImK7idCBTKUB6w7DRTDV/5Ko9+TlZCLOXjbuGNb+InxYQm+H72G8fNPKVcrfcEz

  matrix:
    - VSVER: 9

install:
  - choco install upx --x86 -y
  - RefreshEnv
  - MKDIR package\tools
  - CD package\tools
  - curl -fsSL -o diff.exe https://github.com/wangkexiong/diff.msbuild/releases/download/vc9.x86/diff.exe
  - curl -fsSL -o ctags.exe https://github.com/wangkexiong/exuberant.ctags/releases/download/vc9.x86/ctags.exe
  - curl -fsSL https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msys2-2.7.0-ia32.tar.gz | tar xzvf - --strip-components 2 winpty-0.4.3-msys2-2.7.0-ia32/bin/winpty-agent.exe winpty-0.4.3-msys2-2.7.0-ia32/bin/winpty.dll
  - MOVE winpty.dll winpty32.dll
  - SET "PATH_STORE=%PATH%"
  - SET "PATH=C:\Cygwin\bin;%PATH%"
  - MKDIR gettext32
  - curl -fsSL https://github.com/wangkexiong/build.mxe/releases/download/gettext/gettext4vim-0.19.8.1.x86.tar.xz | tar xJvf - -C gettext32
  - MKDIR gettext64
  - curl -fsSL https://github.com/wangkexiong/build.mxe/releases/download/gettext/gettext4vim-0.19.8.1.amd64.tar.xz | tar xJvf - -C gettext64
  - SET "PATH=%PATH_STORE%"
  - CD ..\..

before_build:
  - ps: >-
      $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))

build_script:
  - start
  - IF EXIST *.exe SET READY_DEPLOY=true
  - IF EXIST *.exe CALL trigger_commit

artifacts:
  - path: '*.exe'

deploy:
  - provider: GitHub
    artifact: /.*\.exe/
    release: $(BUILD_TAG)
    draft: false
    prerelease: false
    force_update: false
    auth_token: $(GITHUB_TOKEN)
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false
      READY_DEPLOY: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

